### ISSUE TITLE
Allow !=/== null

### ISSUE THREAD

**Issue by nikialeksey** [nikialeksey/nullfree#10]
Seems, that comparision with null does not do anything harm. So we can add that ability in plugin configs

**Comment by 0pdd** [comment]
@nikialeksey 2 puzzles [#13](https://github.com/nikialeksey/nullfree/issues/13), [#14](https://github.com/nikialeksey/nullfree/issues/14) are still not solved.

**Comment by 0pdd** [comment]
@nikialeksey the puzzle [#14](https://github.com/nikialeksey/nullfree/issues/14) is still not solved; solved: [#13](https://github.com/nikialeksey/nullfree/issues/13).

**Comment by 0pdd** [comment]
@nikialeksey all 2 puzzles are solved here: [#13](https://github.com/nikialeksey/nullfree/issues/13), [#14](https://github.com/nikialeksey/nullfree/issues/14).
