### ISSUE TITLE
Add crashing build ability, when null was found

### ISSUE THREAD

**Issue by nikialeksey** [nikialeksey/nullfree#2]

**Comment by 0pdd** [comment]
@nikialeksey 2 puzzles [#19](https://github.com/nikialeksey/nullfree/issues/19), [#20](https://github.com/nikialeksey/nullfree/issues/20) are still not solved.

**Comment by 0pdd** [comment]
@nikialeksey the puzzle [#19](https://github.com/nikialeksey/nullfree/issues/19) is still not solved; solved: [#20](https://github.com/nikialeksey/nullfree/issues/20).

**Comment by 0pdd** [comment]
@nikialeksey all 2 puzzles are solved here: [#19](https://github.com/nikialeksey/nullfree/issues/19), [#20](https://github.com/nikialeksey/nullfree/issues/20).
